version: '3.8'

services:
  kubernetes-docs:
    build:
      context: .
      args:
        - VITE_OLLAMA_BASE=${VITE_OLLAMA_BASE:-http://localhost/ollama/v1}
        - VITE_MODEL_NAME=${VITE_MODEL_NAME:-gpt-oss:20b}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
