import React from 'react';
import rancherVideo from '../assets/add_cluster_to_rancher.mp4';

const RancherSetupAddCluster = () => {
  return (
    <div>
      <div className="content-box">
        <h3>Rancher UI Setup Overview</h3>
        <p>Rancher is a complete container management platform that provides centralized multi-cluster Kubernetes management. It simplifies cluster operations, provides a user-friendly web interface, and offers enterprise-grade security and compliance features.</p>
        <p>Rancher can manage clusters across different environments: on-premise, cloud, and edge. It provides cluster provisioning, monitoring, alerting, and application deployment capabilities through a unified interface.</p>
      </div>

      <div className="content-box">
        <h3>Prerequisites</h3>
        <p>Before installing Rancher, ensure you have:</p>
        <ul>
          <li><strong>Docker:</strong> Docker 20.10+ or containerd 1.6+</li>
          <li><strong>System:</strong> 4GB RAM, 2 CPU cores, 20GB disk space</li>
          <li><strong>Network:</strong> Internet access for downloading images</li>
          <li><strong>Domain:</strong> A valid domain name (for production)</li>
          <li><strong>SSL Certificate:</strong> Valid SSL certificate (for production)</li>
        </ul>
      </div>

      <div className="content-box">
        <h3>Step 1: Download Rancher</h3>
        <p>Download the latest Rancher version:</p>
        <pre><code>{`# Download Rancher (replace with latest version)
wget https://github.com/rancher/rancher/releases/download/v2.8.0/rancher-linux-amd64-v2.8.0.tar.gz

# Extract the archive
tar -xzf rancher-linux-amd64-v2.8.0.tar.gz

# Make it executable
chmod +x rancher-v2.8.0/rancher

# Move to system path
sudo mv rancher-v2.8.0/rancher /usr/local/bin/`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Step 2: Install Rancher Server</h3>
        <p>Install Rancher using Docker (recommended for development):</p>
        <pre><code>{`# Run Rancher with Docker
docker run -d --restart=unless-stopped \\
  -p 80:80 -p 443:443 \\
  --privileged \\
  rancher/rancher:latest

# For production with custom domain
docker run -d --restart=unless-stopped \\
  -p 80:80 -p 443:443 \\
  --privileged \\
  -v /opt/rancher:/var/lib/rancher \\
  rancher/rancher:latest \\
  --acme-domain your-domain.com`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Step 3: Access Rancher UI</h3>
        <p>Access the Rancher web interface:</p>
        <pre><code>{`# Access Rancher UI
# Open browser and go to: https://your-server-ip

# Get the initial admin password
docker logs <rancher-container-id> 2>&1 | grep "Bootstrap Password:"

# Or check the logs for the password
docker logs <rancher-container-id>`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Step 4: Initial Setup</h3>
        <p>Complete the initial Rancher setup:</p>
        <ul>
          <li><strong>Set Admin Password:</strong> Change the default bootstrap password</li>
          <li><strong>Server URL:</strong> Set the Rancher server URL (domain or IP)</li>
          <li><strong>Telemetry:</strong> Choose whether to send usage statistics</li>
        </ul>
      </div>

      <div className="content-box">
        <h3>Step 5: Add On-Premise Cluster</h3>
        <p>Add your existing on-premise Kubernetes cluster to Rancher:</p>
        <ol>
          <li><strong>Navigate to Clusters:</strong> Click "Clusters" in the main menu</li>
          <li><strong>Add Cluster:</strong> Click "Add Cluster" button</li>
          <li><strong>Choose Import:</strong> Select "Import an existing cluster"</li>
          <li><strong>Cluster Name:</strong> Enter a descriptive name for your cluster</li>
          <li><strong>Generate Command:</strong> Rancher will generate a kubectl command</li>
        </ol>
      </div>

      <div className="content-box">
        <h3>Step 6: Install Cattle Agent</h3>
        <p>Install the Rancher Cattle agent on your cluster to enable monitoring:</p>
        <pre><code>{`# The command will look like this (generated by Rancher):
kubectl apply -f https://your-rancher-server/v3/import/abc123def456.yaml

# Or using curl:
curl --insecure -sfL https://your-rancher-server/v3/import/abc123def456.yaml | kubectl apply -f -`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Video Tutorial: Adding Cluster to Rancher</h3>
        <p>Watch this video to see the complete process of adding an on-premise cluster to Rancher and installing the Cattle agent:</p>
        
        <div style={{ textAlign: 'center', margin: '20px 0' }}>
          <video 
            controls 
            width="100%" 
            style={{ 
              maxWidth: '800px',
              border: '1px solid #30363d',
              borderRadius: '8px',
              boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)'
            }}
          >
            <source src={rancherVideo} type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <p className="architecture-image-caption">
            Complete Guide: Adding On-Premise Cluster to Rancher
          </p>
        </div>
      </div>

      <div className="content-box">
        <h3>Step 7: Verify Cluster Connection</h3>
        <p>Verify that your cluster is properly connected to Rancher:</p>
        <pre><code>{`# Check cluster status in Rancher UI
# Navigate to Clusters > Your Cluster Name

# Check from command line
kubectl get nodes
kubectl get pods -n cattle-system

# Verify Rancher agent is running
kubectl get pods -n cattle-system -l app=cattle-agent`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Alternative: Helm Installation</h3>
        <p>For production environments, install Rancher using Helm:</p>
        <pre><code>{`# Add Rancher Helm repository
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

# Create namespace
kubectl create namespace cattle-system

# Install Rancher
helm install rancher rancher-latest/rancher \\
  --namespace cattle-system \\
  --set hostname=your-domain.com \\
  --set bootstrapPassword=admin123`}</code></pre>
      </div>

      <div className="content-box">
        <h3>Troubleshooting</h3>
        <p>Common issues and solutions:</p>
        <ul>
          <li><strong>Agent not connecting:</strong> Check firewall rules and network connectivity</li>
          <li><strong>SSL issues:</strong> Ensure valid SSL certificate or use self-signed</li>
          <li><strong>Memory issues:</strong> Increase Docker memory allocation</li>
          <li><strong>Port conflicts:</strong> Ensure ports 80 and 443 are available</li>
        </ul>
        <p><a className="link" href="https://ranchermanager.docs.rancher.com/" target="_blank" rel="noreferrer">Official Rancher Documentation</a></p>
      </div>
    </div>
  );
};

export default RancherSetupAddCluster;
